from __future__ import annotations

import re
from typing import Iterable, Mapping


VARIABLE_INFO: dict[str, tuple[str, str]] = {
    "user": ("TestViewer", "Viewer or account display name"),
    "user_id": ("123456", "Twitch user ID"),
    "user_login": ("testviewer", "Triggering viewer Twitch login"),
    "viewer_permission": ("everyone", "Triggering viewer's highest command permission"),
    "target_user_id": ("654321", "Target Twitch user ID"),
    "channel": ("samplechannel", "Broadcaster channel name"),
    "message": ("Hello Sally!", "Chat message or event text"),
    "message_id": ("message-123", "Twitch chat message ID"),
    "command": ("hello", "Chat command name without !"),
    "args": ("friend", "Text following a chat command"),
    "target": ("friend", "First command argument, without @"),
    "uses": ("3", "Number of times the command has run"),
    "event": ("Follow", "Readable trigger event name"),
    "event_type": ("channel.follow", "Raw service event type"),
    "input": ("Viewer supplied text", "Reward input or OBS input name"),
    "amount": ("100", "Event amount, viewers, bits, or reward cost"),
    "bits": ("100", "Number of cheered bits"),
    "viewers": ("12", "Viewer or raid count"),
    "tier": ("1000", "Twitch subscription tier"),
    "reward": ("Hydrate", "Channel-point reward title"),
    "reward_id": ("reward-123", "Channel-point reward ID"),
    "reward_cost": ("500", "Channel-point reward cost"),
    "redemption_id": ("redemption-123", "Channel-point redemption ID"),
    "title": ("Building Sally", "Current stream title"),
    "game": ("Science & Technology", "Current Twitch category"),
    "uptime": ("01:23:45", "Current stream uptime"),
    "followers": ("445", "Current follower count"),
    "scene": ("Gameplay", "OBS scene name"),
    "source": ("Camera", "OBS scene source name"),
    "output_state": ("OBS_WEBSOCKET_OUTPUT_STARTED", "OBS output state"),
    "enabled": ("true", "OBS source or Studio Mode state"),
    "mute": ("Not Muted", "OBS input mute state"),
    "muted": ("Not Muted", "OBS input mute state"),
    "volume_db": ("-8.0", "OBS input volume in decibels"),
    "media": ("Intro Video", "OBS media input name"),
    "target_login": ("targetviewer", "Resolved target Twitch login"),
    "target_display_name": ("TargetViewer", "Resolved target display name"),
    "account_created_at": ("2020-01-02T03:04:05Z", "Twitch account creation time"),
    "user_lookup_status": ("found", "Twitch user lookup result"),
    "stream_status": ("live", "Live, offline, or API error result"),
    "is_live": ("true", "Whether the broadcaster is currently live"),
    "stream_started_at": ("2026-08-02T12:00:00Z", "Current stream start time"),
    "stream_title": ("Building Streamhouse", "Current Twitch channel title"),
    "stream_category": ("Science & Technology", "Current Twitch category"),
    "stream_id": ("stream-123", "Current Twitch stream ID"),
    "stream_viewers": ("12", "Current live viewer count"),
    "stream_game_id": ("509670", "Current Twitch category ID"),
    "channel_info_status": ("available", "Channel information lookup result"),
    "title_status": ("available", "Channel title lookup result"),
    "category_status": ("set", "Channel category lookup result"),
    "is_following": ("true", "Whether the target follows the broadcaster"),
    "followed_at": ("2024-01-02T03:04:05Z", "When the target followed the channel"),
    "follow_status": ("following", "Follow relationship lookup result"),
    "channel_display_name": ("SampleChannel", "Broadcaster display name"),
    "formatted_duration": ("2 hours 18 minutes", "Human-readable duration"),
    "formatted_duration_status": ("available", "Duration formatting result"),
    "command_list": ("!uptime, !title", "Enabled commands visible to the viewer"),
    "command_list_status": ("available", "Command-list build result"),
    "command_response": ("The channel is currently offline.", "Selected command response"),
    "followage": ("4 months 6 days", "Human-readable follow age"),
    "followage_status": ("available", "Follow-age formatting result"),
    "account_age": ("1 year 2 months", "Human-readable Twitch account age"),
    "account_age_status": ("available", "Account-age formatting result"),
}

VARIABLE_SOURCE_INFO: dict[str, str] = {
    "user": "Trigger context",
    "user_id": "Trigger context",
    "user_login": "Twitch command",
    "viewer_permission": "Twitch command",
    "target_user_id": "Trigger context",
    "channel": "Twitch context",
    "message": "Trigger context",
    "message_id": "Trigger context",
    "command": "Twitch command",
    "args": "Twitch command",
    "target": "Twitch command",
    "uses": "Twitch command",
    "event": "Trigger context",
    "event_type": "Trigger context",
    "input": "Trigger context",
    "amount": "Trigger context",
    "bits": "Twitch event",
    "viewers": "Twitch event",
    "tier": "Twitch event",
    "reward": "Twitch reward",
    "reward_id": "Twitch reward",
    "reward_cost": "Twitch reward",
    "redemption_id": "Twitch reward",
    "title": "Twitch live context",
    "game": "Twitch live context",
    "uptime": "Twitch live context",
    "followers": "Twitch live context",
    "scene": "OBS event",
    "source": "OBS event",
    "output_state": "OBS event",
    "enabled": "OBS event",
    "mute": "OBS runtime lookup",
    "muted": "OBS runtime lookup",
    "volume_db": "OBS event",
    "media": "OBS event",
    "target_login": "Resolve User task",
    "target_display_name": "Resolve User task",
    "account_created_at": "Resolve User task",
    "user_lookup_status": "Resolve User task",
    "stream_status": "Get Stream Information task",
    "is_live": "Get Stream Information task",
    "stream_started_at": "Get Stream Information task",
    "stream_title": "Twitch information task",
    "stream_category": "Twitch information task",
    "stream_id": "Get Stream Information task",
    "stream_viewers": "Get Stream Information task",
    "stream_game_id": "Twitch information task",
    "channel_info_status": "Get Channel Information task",
    "title_status": "Get Channel Information task",
    "category_status": "Get Channel Information task",
    "is_following": "Get Follow Relationship task",
    "followed_at": "Get Follow Relationship task",
    "follow_status": "Get Follow Relationship task",
    "channel_display_name": "Twitch context",
    "formatted_duration": "Format Duration task",
    "formatted_duration_status": "Format Duration task",
    "command_list": "Build Command List task",
    "command_list_status": "Build Command List task",
    "command_response": "Select Text task",
    "followage": "Format Duration task",
    "followage_status": "Format Duration task",
    "account_age": "Format Duration task",
    "account_age_status": "Format Duration task",
}


TWITCH_VARIABLES = tuple(VARIABLE_INFO)
OBS_VARIABLES = (
    "event",
    "event_type",
    "scene",
    "source",
    "input",
    "output_state",
    "enabled",
    "mute",
    "muted",
    "volume_db",
    "media",
    "channel",
    "user",
    "message",
)
CORE_VARIABLES = (
    "event",
    "event_type",
    "channel",
    "user",
    "title",
    "game",
    "uptime",
    "followers",
)

TEMPLATE_PATTERN = re.compile(r"\{([a-z][a-z0-9_]*)\}")


def sample_context(keys: Iterable[str]) -> dict[str, str]:
    requested = set(keys)
    return {
        key: sample
        for key, (sample, _description) in VARIABLE_INFO.items()
        if key in requested
    }


def render_preview(template: str, context: Mapping[str, str]) -> str:
    return TEMPLATE_PATTERN.sub(
        lambda match: str(
            context.get(match.group(1), f"{{{match.group(1)}}}")
        ).strip(),
        template,
    )
